BI-8147 Create profile file for cidev environment
companieshouse/data-reconciliation-terraform pull request #25
Opened 2021-06-16 10:52 UTC by dlgroves-ch

* Configuration duplicated from tbirds1 environment.

2021-06-16 11:50 UTC, kinpang-CH approved these changes, later dismissed

2021-06-16 14:10 UTC, phudson-ch approved these changes

2021-06-16 15:36 UTC, phudson-ch requested changes
Needs company_status_mongo_oracle_delay

2021-06-17 11:01 UTC, phudson-ch approved these changes

2021-06-17 11:01 UTC, kinpang-CH approved these changes

2021-06-17 11:02 UTC, merged