BI-8148 Add staging profile to data-reconciliation app
companieshouse/data-reconciliation-terraform pull request #28
Opened 2021-06-16 14:29 UTC by dlgroves-ch

* Based on deployment values on tbirds1 environment.

2021-06-16 14:52 UTC, kinpang-CH approved these changes, later dismissed

2021-06-16 15:26 UTC, phudson-ch approved these changes

2021-06-16 15:31 UTC, phudson-ch requested changes
Needs company_status_mongo_oracle_delay

2021-06-28 07:41 UTC, phudson-ch submitted a review, later dismissed

2021-06-28 08:36 UTC, phudson-ch approved these changes

2021-06-28 08:41 UTC, cgregoryCH approved these changes

2021-06-28 08:49 UTC, kinpang-CH approved these changes

2021-06-28 13:51 UTC, merged