BI-8149 Implement live profile
companieshouse/data-reconciliation-terraform pull request #29
Opened 2021-06-16 14:33 UTC by dlgroves-ch

* Deployment properties derived from TBirds1 environment.

2021-06-16 14:53 UTC, kinpang-CH submitted a review, later dismissed

2021-06-16 15:30 UTC, phudson-ch requested changes
Also needs company_status_mongo_oracle_delay

2021-06-30 12:42 UTC, phudson-ch approved these changes

2021-06-30 12:43 UTC, kinpang-CH approved these changes

2021-06-30 12:45 UTC, cgregoryCH approved these changes

2021-06-30 16:24 UTC, merged